### ISSUE TITLE
flake8-typing-imports fails with ValueError for min_python_version set to 3.11 or 3.10 in setup.cfg

### ISSUE THREAD

**Issue by boutsitron** [asottile/flake8-typing-imports#173]
**Issue Description:**

When setting the `min_python_version` in `setup.cfg` to either `3.11` or `3.10`, `flake8` works perfectly fine, but `flake8-typing-imports` encounters an issue. 

Example configuration in `setup.cfg`:
```
[flake8]
min_python_version = 3.11
```

or even

```
[flake8]
min_python_version = 3.10
```

The error encountered using Python 3.11 is: `ValueError: min-python-version (3.11.0): unknown version`

**Steps to Reproduce:**
1. Set `min_python_version` to `3.11` or `3.10` in `setup.cfg`.
2. Run `flake8` with `flake8-typing-imports` enabled.

**Expected Behavior:**
`flake8-typing-imports` should work without any issues when the `min_python_version` is set to `3.11` or `3.10`.

**Actual Behavior:**
`flake8-typing-imports` fails with a `ValueError` indicating an unknown version.

**Additional Information:**
- `flake8` version: 5.0.4 (flake8-docstrings: 1.6.0, mccabe: 0.7.0, pycodestyle: 2.9.1, pyflakes: 2.5.0) CPython 3.11.8 on Darwin
- `Python` version: Python 3.11.8

**Comment by asottile** [comment]
you're using an ancient version which did not know about those python versions
