### ISSUE TITLE
Error for Versions > 3.7.4

### ISSUE THREAD

**Issue by Cielquan** [asottile/flake8-typing-imports#19]
When I set a version in "python_requires" in setup.cfg that is > 3.7.4, which is the current max (version 1.8) in the generated 'SYMBOLS' frozenset, I get a ValueError from the `Plugin.parse_options` classmethod. Maybe the if-block `if v not in VERSIONS` can be omitted? 

I do not see a reason to keep it because on lower versions its overwritten with 3.5 and newer versions do exist.

**Comment by asottile** [comment]
probably just needs the symbols to be regenned
