### ISSUE TITLE
Detect attributes from typing alias

### ISSUE THREAD

**Issue by davidism** [asottile/flake8-typing-imports#48]
#17 allowed `typing.NoReturn` instead of `NoReturn`, but we do `import typing as t` for a shorter name.

I know this is similar to the `typing.overload` issue in https://github.com/PyCQA/pyflakes/issues/561. Alternatively, maybe this can be addressed with a config option like `typing_namespace = t` to change what name the plugin looks for.

I was trying to run this on our projects as someone brought up an issue with the import in 3.6.0, but was surprised to see no errors reported. Not a huge deal, I can just reference the supported list in your code and do it manually for now.

**Comment by asottile** [comment]
I'd rather not, the prevailing convention is to import from `typing` -- aliasing is a slipperly slope down trying to solve the halting problem (what about `import typing; x = typing`? what if that's conditional?) -- it's basically intractable

I'd recommend not going against the grain and importing `from typing ...` directly

**Comment by davidism** [comment]
https://github.com/PyCQA/pyflakes/issues/561#issuecomment-725709789 seems relevant here as well. If someone solves it there, maybe we can revisit this.
