### ISSUE TITLE
Python version patch level is ignore

### ISSUE THREAD

**Issue by kasium** [asottile/flake8-typing-imports#61]
Given **foo.py**
```python
from typing import OrderedDict
```

Execute: ``flake8 --select TYP --min-python-version 3.7.2 foo.py``

```
foo.py:1:1: TYP001 guard import by `if TYPE_CHECKING:`: OrderedDict (not in 3.7.0, 3.7.1)
```

This is not expected since I specified the minimum version of 3.7.2. I di some debugging in your code and the version is correctly read from the configuration but during the check the patch level is somehow erased from the version object

**Comment by asottile** [comment]
cannot reproduce:

```console
$ flake8 t.py --select TYP --min-python-version 3.7.2
$
```

**Comment by kasium** [comment]
Can you please try with python  3.7.1 installed?

**Comment by asottile** [comment]
```console
root@0857c1d741f3:/# python --version
Python 3.7.1
root@0857c1d741f3:/# flake8 f.py --select TYP --min-python-version 3.7.2
root@0857c1d741f3:/#
```

**Comment by kasium** [comment]
Thanks a lot. I cleaned the whole project (should have done this before) and now the issue is gone 👍
