### ISSUE TITLE
Release package as a typed one

### ISSUE THREAD

**Issue by kasium** [asottile/flake8-typing-imports#65]
Hello,

I really love this flake8 plugin, so thanks a lot for creating it. I working on a flake8 plugin which has own rules but also wraps other plugins, also this one. I know that this is not in scope of this project, but it would be great if you could add a py.typed file somehow, so that user importing the script as code can benefit from the already present types.

I'm happy to contribute if you like.

Thanks,
Kai

**Comment by asottile** [comment]
I don't intend to provide a programmatic api
